---
base_packages:
  - vlan
  - nftables
  - iptables
  - jq
  - curl
  - openssl
  - ca-certificates
  - python3-cryptography
  - python3-netaddr
  - bridge-utils
  - chrony
ntp_service: chrony
ntp_conf: /etc/chrony/chrony.conf
ca_trust_dir: /usr/local/share/ca-certificates
ca_trust_update_cmd: update-ca-certificates
