---
base_packages:
  - nftables
  - iptables
  - jq
  - curl
  - openssl
  - ca-certificates
  - python3-cryptography
  - python3-netaddr
  - chrony
ntp_service: chronyd
ntp_conf: /etc/chrony.conf
ca_trust_dir: /etc/pki/ca-trust/source/anchors
ca_trust_update_cmd: update-ca-trust
